//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.10 at 12:30:15 PM CLT 
//


package cl.caserita.respuestaLarga;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Codigo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="50"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="-1"/>
 *               &lt;enumeration value="-2"/>
 *               &lt;enumeration value="-3"/>
 *               &lt;enumeration value="-4"/>
 *               &lt;enumeration value="-5"/>
 *               &lt;enumeration value="-6"/>
 *               &lt;enumeration value="-7"/>
 *               &lt;enumeration value="-8"/>
 *               &lt;enumeration value="-9"/>
 *               &lt;enumeration value="-10"/>
 *               &lt;enumeration value="-11"/>
 *               &lt;enumeration value="-12"/>
 *               &lt;enumeration value="-13"/>
 *               &lt;enumeration value="-14"/>
 *               &lt;enumeration value="-15"/>
 *               &lt;enumeration value="-16"/>
 *               &lt;enumeration value="-17"/>
 *               &lt;enumeration value="-18"/>
 *               &lt;enumeration value="-19"/>
 *               &lt;enumeration value="-20"/>
 *               &lt;enumeration value="-21"/>
 *               &lt;enumeration value="-21"/>
 *               &lt;enumeration value="-22"/>
 *               &lt;enumeration value="-24"/>
 *               &lt;enumeration value="-25"/>
 *               &lt;enumeration value="-26"/>
 *               &lt;enumeration value="-30"/>
 *               &lt;enumeration value="-50"/>
 *               &lt;enumeration value="-98"/>
 *               &lt;enumeration value="-99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Mensaje">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="900"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigo",
    "mensaje"
})
@XmlRootElement(name = "Respuesta")
public class Respuesta {

    @XmlElement(name = "Codigo")
    protected int codigo;
    @XmlElement(name = "Mensaje", required = true)
    protected String mensaje;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the codigo property.
     * 
     */
    public int getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     */
    public void setCodigo(int value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje(String value) {
        this.mensaje = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
