//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.07 at 02:26:28 PM CLST 
//


package cl.paperless.boleta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.paperless.boleta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _Personalizados_QNAME = new QName("http://www.sii.cl/SiiDte", "Personalizados");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.paperless.boleta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms.Transform }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms.Transform createSignatureTypeSignedInfoReferenceTransformsTransform() {
        return new SignatureType.SignedInfo.Reference.Transforms.Transform();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.DscRcgGlobal }
     * 
     */
    public BOLETADefType.Documento.DscRcgGlobal createBOLETADefTypeDocumentoDscRcgGlobal() {
        return new BOLETADefType.Documento.DscRcgGlobal();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF createBOLETADefTypeDocumentoTEDDDCAF() {
        return new BOLETADefType.Documento.TED.DD.CAF();
    }

    /**
     * Create an instance of {@link EnvioBOLETA.SetDTE }
     * 
     */
    public EnvioBOLETA.SetDTE createEnvioBOLETASetDTE() {
        return new EnvioBOLETA.SetDTE();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD }
     * 
     */
    public BOLETADefType.Documento.TED.DD createBOLETADefTypeDocumentoTEDDD() {
        return new BOLETADefType.Documento.TED.DD();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF.DA.RSAPK }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF.DA.RSAPK createBOLETADefTypeDocumentoTEDDDCAFDARSAPK() {
        return new BOLETADefType.Documento.TED.DD.CAF.DA.RSAPK();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Encabezado.Emisor }
     * 
     */
    public BOLETADefType.Documento.Encabezado.Emisor createBOLETADefTypeDocumentoEncabezadoEmisor() {
        return new BOLETADefType.Documento.Encabezado.Emisor();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado.ImpresionDetalle }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado.ImpresionDetalle createPersonalizadosDefTypeDocPersonalizadoImpresionDetalle() {
        return new PersonalizadosDefType.DocPersonalizado.ImpresionDetalle();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType }
     * 
     */
    public PersonalizadosDefType createPersonalizadosDefType() {
        return new PersonalizadosDefType();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.X509Data }
     * 
     */
    public SignatureType.KeyInfo.X509Data createSignatureTypeKeyInfoX509Data() {
        return new SignatureType.KeyInfo.X509Data();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF.DA.RNG }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF.DA.RNG createBOLETADefTypeDocumentoTEDDDCAFDARNG() {
        return new BOLETADefType.Documento.TED.DD.CAF.DA.RNG();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Encabezado }
     * 
     */
    public BOLETADefType.Documento.Encabezado createBOLETADefTypeDocumentoEncabezado() {
        return new BOLETADefType.Documento.Encabezado();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Encabezado.Totales }
     * 
     */
    public BOLETADefType.Documento.Encabezado.Totales createBOLETADefTypeDocumentoEncabezadoTotales() {
        return new BOLETADefType.Documento.Encabezado.Totales();
    }

    /**
     * Create an instance of {@link EnvioBOLETA }
     * 
     */
    public EnvioBOLETA createEnvioBOLETA() {
        return new EnvioBOLETA();
    }

    /**
     * Create an instance of {@link EnvioBOLETA.SetDTE.Caratula.SubTotDTE }
     * 
     */
    public EnvioBOLETA.SetDTE.Caratula.SubTotDTE createEnvioBOLETASetDTECaratulaSubTotDTE() {
        return new EnvioBOLETA.SetDTE.Caratula.SubTotDTE();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue createSignatureTypeKeyInfoKeyValue() {
        return new SignatureType.KeyInfo.KeyValue();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF.DA }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF.DA createBOLETADefTypeDocumentoTEDDDCAFDA() {
        return new BOLETADefType.Documento.TED.DD.CAF.DA();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo }
     * 
     */
    public SignatureType.KeyInfo createSignatureTypeKeyInfo() {
        return new SignatureType.KeyInfo();
    }

    /**
     * Create an instance of {@link BOLETADefType }
     * 
     */
    public BOLETADefType createBOLETADefType() {
        return new BOLETADefType();
    }

    /**
     * Create an instance of {@link EnvioBOLETA.SetDTE.Caratula }
     * 
     */
    public EnvioBOLETA.SetDTE.Caratula createEnvioBOLETASetDTECaratula() {
        return new EnvioBOLETA.SetDTE.Caratula();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado.Impresion }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado.Impresion createPersonalizadosDefTypeDocPersonalizadoImpresion() {
        return new PersonalizadosDefType.DocPersonalizado.Impresion();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Encabezado.IdDoc }
     * 
     */
    public BOLETADefType.Documento.Encabezado.IdDoc createBOLETADefTypeDocumentoEncabezadoIdDoc() {
        return new BOLETADefType.Documento.Encabezado.IdDoc();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento }
     * 
     */
    public BOLETADefType.Documento createBOLETADefTypeDocumento() {
        return new BOLETADefType.Documento();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado createPersonalizadosDefTypeDocPersonalizado() {
        return new PersonalizadosDefType.DocPersonalizado();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED }
     * 
     */
    public BOLETADefType.Documento.TED createBOLETADefTypeDocumentoTED() {
        return new BOLETADefType.Documento.TED();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference }
     * 
     */
    public SignatureType.SignedInfo.Reference createSignatureTypeSignedInfoReference() {
        return new SignatureType.SignedInfo.Reference();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.DigestMethod }
     * 
     */
    public SignatureType.SignedInfo.Reference.DigestMethod createSignatureTypeSignedInfoReferenceDigestMethod() {
        return new SignatureType.SignedInfo.Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF.DA.DSAPK }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF.DA.DSAPK createBOLETADefTypeDocumentoTEDDDCAFDADSAPK() {
        return new BOLETADefType.Documento.TED.DD.CAF.DA.DSAPK();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Encabezado.Receptor }
     * 
     */
    public BOLETADefType.Documento.Encabezado.Receptor createBOLETADefTypeDocumentoEncabezadoReceptor() {
        return new BOLETADefType.Documento.Encabezado.Receptor();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo }
     * 
     */
    public SignatureType.SignedInfo createSignatureTypeSignedInfo() {
        return new SignatureType.SignedInfo();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.SubTotInfo }
     * 
     */
    public BOLETADefType.Documento.SubTotInfo createBOLETADefTypeDocumentoSubTotInfo() {
        return new BOLETADefType.Documento.SubTotInfo();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.DSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.DSAKeyValue createSignatureTypeKeyInfoKeyValueDSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.DSAKeyValue();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.RSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.RSAKeyValue createSignatureTypeKeyInfoKeyValueRSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.RSAKeyValue();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado.CampoFecha }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado.CampoFecha createPersonalizadosDefTypeDocPersonalizadoCampoFecha() {
        return new PersonalizadosDefType.DocPersonalizado.CampoFecha();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado.CampoNumero }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado.CampoNumero createPersonalizadosDefTypeDocPersonalizadoCampoNumero() {
        return new PersonalizadosDefType.DocPersonalizado.CampoNumero();
    }

    /**
     * Create an instance of {@link PersonalizadosDefType.DocPersonalizado.CampoString }
     * 
     */
    public PersonalizadosDefType.DocPersonalizado.CampoString createPersonalizadosDefTypeDocPersonalizadoCampoString() {
        return new PersonalizadosDefType.DocPersonalizado.CampoString();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Detalle.CdgItem }
     * 
     */
    public BOLETADefType.Documento.Detalle.CdgItem createBOLETADefTypeDocumentoDetalleCdgItem() {
        return new BOLETADefType.Documento.Detalle.CdgItem();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.CanonicalizationMethod }
     * 
     */
    public SignatureType.SignedInfo.CanonicalizationMethod createSignatureTypeSignedInfoCanonicalizationMethod() {
        return new SignatureType.SignedInfo.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Detalle }
     * 
     */
    public BOLETADefType.Documento.Detalle createBOLETADefTypeDocumentoDetalle() {
        return new BOLETADefType.Documento.Detalle();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.SignatureMethod }
     * 
     */
    public SignatureType.SignedInfo.SignatureMethod createSignatureTypeSignedInfoSignatureMethod() {
        return new SignatureType.SignedInfo.SignatureMethod();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms createSignatureTypeSignedInfoReferenceTransforms() {
        return new SignatureType.SignedInfo.Reference.Transforms();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.FRMT }
     * 
     */
    public BOLETADefType.Documento.TED.FRMT createBOLETADefTypeDocumentoTEDFRMT() {
        return new BOLETADefType.Documento.TED.FRMT();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.TED.DD.CAF.FRMA }
     * 
     */
    public BOLETADefType.Documento.TED.DD.CAF.FRMA createBOLETADefTypeDocumentoTEDDDCAFFRMA() {
        return new BOLETADefType.Documento.TED.DD.CAF.FRMA();
    }

    /**
     * Create an instance of {@link BOLETADefType.Documento.Referencia }
     * 
     */
    public BOLETADefType.Documento.Referencia createBOLETADefTypeDocumentoReferencia() {
        return new BOLETADefType.Documento.Referencia();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalizadosDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sii.cl/SiiDte", name = "Personalizados")
    public JAXBElement<PersonalizadosDefType> createPersonalizados(PersonalizadosDefType value) {
        return new JAXBElement<PersonalizadosDefType>(_Personalizados_QNAME, PersonalizadosDefType.class, null, value);
    }

}
