//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.07 at 02:26:28 PM CLST 
//


package cl.paperless.boleta;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PersonalizadosDefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalizadosDefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocPersonalizado" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="campoString" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="campoNumero" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="campoFecha" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Impresion" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Personalizado_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_15" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_16" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_17" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_18" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_19" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_20" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Personalizado_21" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="Personalizado_22" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="Personalizado_23" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="Personalizado_24" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Personalizado_25" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Personalizado_26" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Personalizado_27" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="Personalizado_28" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="Personalizado_29" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ImpresionDetalle" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PersonNroLinDet" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="DetPersonAFN_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonAFN_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_01" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_02" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_03" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_04" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_05" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_06" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_07" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_08" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_09" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUE_10" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_01" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_02" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_03" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_04" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_05" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_06" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_07" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_08" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_09" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonNUD_10" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="DetPersonFEC_01" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="DetPersonFEC_02" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="dteID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalizadosDefType", namespace = "http://www.sii.cl/SiiDte", propOrder = {
    "docPersonalizado"
})
public class PersonalizadosDefType {

    @XmlElement(name = "DocPersonalizado")
    protected List<PersonalizadosDefType.DocPersonalizado> docPersonalizado;

    /**
     * Gets the value of the docPersonalizado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docPersonalizado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocPersonalizado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonalizadosDefType.DocPersonalizado }
     * 
     * 
     */
    public List<PersonalizadosDefType.DocPersonalizado> getDocPersonalizado() {
        if (docPersonalizado == null) {
            docPersonalizado = new ArrayList<PersonalizadosDefType.DocPersonalizado>();
        }
        return this.docPersonalizado;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="campoString" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="campoNumero" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="campoFecha" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Impresion" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Personalizado_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_15" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_16" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_17" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_18" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_19" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_20" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Personalizado_21" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="Personalizado_22" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="Personalizado_23" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="Personalizado_24" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Personalizado_25" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Personalizado_26" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Personalizado_27" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="Personalizado_28" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="Personalizado_29" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ImpresionDetalle" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PersonNroLinDet" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="DetPersonAFN_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonAFN_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_01" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_02" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_03" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_04" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_05" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_06" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_07" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_08" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_09" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUE_10" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_01" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_02" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_03" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_04" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_05" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_06" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_07" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_08" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_09" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonNUD_10" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="DetPersonFEC_01" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="DetPersonFEC_02" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="dteID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "campoString",
        "campoNumero",
        "campoFecha",
        "impresion",
        "impresionDetalle"
    })
    public static class DocPersonalizado {

        protected List<PersonalizadosDefType.DocPersonalizado.CampoString> campoString;
        protected List<PersonalizadosDefType.DocPersonalizado.CampoNumero> campoNumero;
        protected List<PersonalizadosDefType.DocPersonalizado.CampoFecha> campoFecha;
        @XmlElement(name = "Impresion")
        protected PersonalizadosDefType.DocPersonalizado.Impresion impresion;
        @XmlElement(name = "ImpresionDetalle")
        protected List<PersonalizadosDefType.DocPersonalizado.ImpresionDetalle> impresionDetalle;
        @XmlAttribute(required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object dteID;

        /**
         * Gets the value of the campoString property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campoString property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampoString().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalizadosDefType.DocPersonalizado.CampoString }
         * 
         * 
         */
        public List<PersonalizadosDefType.DocPersonalizado.CampoString> getCampoString() {
            if (campoString == null) {
                campoString = new ArrayList<PersonalizadosDefType.DocPersonalizado.CampoString>();
            }
            return this.campoString;
        }

        /**
         * Gets the value of the campoNumero property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campoNumero property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampoNumero().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalizadosDefType.DocPersonalizado.CampoNumero }
         * 
         * 
         */
        public List<PersonalizadosDefType.DocPersonalizado.CampoNumero> getCampoNumero() {
            if (campoNumero == null) {
                campoNumero = new ArrayList<PersonalizadosDefType.DocPersonalizado.CampoNumero>();
            }
            return this.campoNumero;
        }

        /**
         * Gets the value of the campoFecha property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campoFecha property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampoFecha().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalizadosDefType.DocPersonalizado.CampoFecha }
         * 
         * 
         */
        public List<PersonalizadosDefType.DocPersonalizado.CampoFecha> getCampoFecha() {
            if (campoFecha == null) {
                campoFecha = new ArrayList<PersonalizadosDefType.DocPersonalizado.CampoFecha>();
            }
            return this.campoFecha;
        }

        /**
         * Gets the value of the impresion property.
         * 
         * @return
         *     possible object is
         *     {@link PersonalizadosDefType.DocPersonalizado.Impresion }
         *     
         */
        public PersonalizadosDefType.DocPersonalizado.Impresion getImpresion() {
            return impresion;
        }

        /**
         * Sets the value of the impresion property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonalizadosDefType.DocPersonalizado.Impresion }
         *     
         */
        public void setImpresion(PersonalizadosDefType.DocPersonalizado.Impresion value) {
            this.impresion = value;
        }

        /**
         * Gets the value of the impresionDetalle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the impresionDetalle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImpresionDetalle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalizadosDefType.DocPersonalizado.ImpresionDetalle }
         * 
         * 
         */
        public List<PersonalizadosDefType.DocPersonalizado.ImpresionDetalle> getImpresionDetalle() {
            if (impresionDetalle == null) {
                impresionDetalle = new ArrayList<PersonalizadosDefType.DocPersonalizado.ImpresionDetalle>();
            }
            return this.impresionDetalle;
        }

        /**
         * Gets the value of the dteID property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDteID() {
            return dteID;
        }

        /**
         * Sets the value of the dteID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDteID(Object value) {
            this.dteID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CampoFecha {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CampoNumero {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CampoString {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Personalizado_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_15" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_16" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_17" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_18" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_19" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_20" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Personalizado_21" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="Personalizado_22" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="Personalizado_23" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="Personalizado_24" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Personalizado_25" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Personalizado_26" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Personalizado_27" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="Personalizado_28" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="Personalizado_29" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "personalizado01",
            "personalizado02",
            "personalizado03",
            "personalizado04",
            "personalizado05",
            "personalizado06",
            "personalizado07",
            "personalizado08",
            "personalizado09",
            "personalizado10",
            "personalizado11",
            "personalizado12",
            "personalizado13",
            "personalizado14",
            "personalizado15",
            "personalizado16",
            "personalizado17",
            "personalizado18",
            "personalizado19",
            "personalizado20",
            "personalizado21",
            "personalizado22",
            "personalizado23",
            "personalizado24",
            "personalizado25",
            "personalizado26",
            "personalizado27",
            "personalizado28",
            "personalizado29"
        })
        public static class Impresion {

            @XmlElement(name = "Personalizado_01")
            protected String personalizado01;
            @XmlElement(name = "Personalizado_02")
            protected String personalizado02;
            @XmlElement(name = "Personalizado_03")
            protected String personalizado03;
            @XmlElement(name = "Personalizado_04")
            protected String personalizado04;
            @XmlElement(name = "Personalizado_05")
            protected String personalizado05;
            @XmlElement(name = "Personalizado_06")
            protected String personalizado06;
            @XmlElement(name = "Personalizado_07")
            protected String personalizado07;
            @XmlElement(name = "Personalizado_08")
            protected String personalizado08;
            @XmlElement(name = "Personalizado_09")
            protected String personalizado09;
            @XmlElement(name = "Personalizado_10")
            protected String personalizado10;
            @XmlElement(name = "Personalizado_11")
            protected String personalizado11;
            @XmlElement(name = "Personalizado_12")
            protected String personalizado12;
            @XmlElement(name = "Personalizado_13")
            protected String personalizado13;
            @XmlElement(name = "Personalizado_14")
            protected String personalizado14;
            @XmlElement(name = "Personalizado_15")
            protected String personalizado15;
            @XmlElement(name = "Personalizado_16")
            protected String personalizado16;
            @XmlElement(name = "Personalizado_17")
            protected String personalizado17;
            @XmlElement(name = "Personalizado_18")
            protected String personalizado18;
            @XmlElement(name = "Personalizado_19")
            protected String personalizado19;
            @XmlElement(name = "Personalizado_20")
            protected String personalizado20;
            @XmlElement(name = "Personalizado_21")
            protected BigInteger personalizado21;
            @XmlElement(name = "Personalizado_22")
            protected BigInteger personalizado22;
            @XmlElement(name = "Personalizado_23")
            protected BigInteger personalizado23;
            @XmlElement(name = "Personalizado_24")
            protected BigDecimal personalizado24;
            @XmlElement(name = "Personalizado_25")
            protected BigDecimal personalizado25;
            @XmlElement(name = "Personalizado_26")
            protected BigDecimal personalizado26;
            @XmlElement(name = "Personalizado_27")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar personalizado27;
            @XmlElement(name = "Personalizado_28")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar personalizado28;
            @XmlElement(name = "Personalizado_29")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar personalizado29;

            /**
             * Gets the value of the personalizado01 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado01() {
                return personalizado01;
            }

            /**
             * Sets the value of the personalizado01 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado01(String value) {
                this.personalizado01 = value;
            }

            /**
             * Gets the value of the personalizado02 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado02() {
                return personalizado02;
            }

            /**
             * Sets the value of the personalizado02 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado02(String value) {
                this.personalizado02 = value;
            }

            /**
             * Gets the value of the personalizado03 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado03() {
                return personalizado03;
            }

            /**
             * Sets the value of the personalizado03 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado03(String value) {
                this.personalizado03 = value;
            }

            /**
             * Gets the value of the personalizado04 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado04() {
                return personalizado04;
            }

            /**
             * Sets the value of the personalizado04 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado04(String value) {
                this.personalizado04 = value;
            }

            /**
             * Gets the value of the personalizado05 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado05() {
                return personalizado05;
            }

            /**
             * Sets the value of the personalizado05 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado05(String value) {
                this.personalizado05 = value;
            }

            /**
             * Gets the value of the personalizado06 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado06() {
                return personalizado06;
            }

            /**
             * Sets the value of the personalizado06 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado06(String value) {
                this.personalizado06 = value;
            }

            /**
             * Gets the value of the personalizado07 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado07() {
                return personalizado07;
            }

            /**
             * Sets the value of the personalizado07 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado07(String value) {
                this.personalizado07 = value;
            }

            /**
             * Gets the value of the personalizado08 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado08() {
                return personalizado08;
            }

            /**
             * Sets the value of the personalizado08 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado08(String value) {
                this.personalizado08 = value;
            }

            /**
             * Gets the value of the personalizado09 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado09() {
                return personalizado09;
            }

            /**
             * Sets the value of the personalizado09 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado09(String value) {
                this.personalizado09 = value;
            }

            /**
             * Gets the value of the personalizado10 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado10() {
                return personalizado10;
            }

            /**
             * Sets the value of the personalizado10 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado10(String value) {
                this.personalizado10 = value;
            }

            /**
             * Gets the value of the personalizado11 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado11() {
                return personalizado11;
            }

            /**
             * Sets the value of the personalizado11 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado11(String value) {
                this.personalizado11 = value;
            }

            /**
             * Gets the value of the personalizado12 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado12() {
                return personalizado12;
            }

            /**
             * Sets the value of the personalizado12 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado12(String value) {
                this.personalizado12 = value;
            }

            /**
             * Gets the value of the personalizado13 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado13() {
                return personalizado13;
            }

            /**
             * Sets the value of the personalizado13 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado13(String value) {
                this.personalizado13 = value;
            }

            /**
             * Gets the value of the personalizado14 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado14() {
                return personalizado14;
            }

            /**
             * Sets the value of the personalizado14 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado14(String value) {
                this.personalizado14 = value;
            }

            /**
             * Gets the value of the personalizado15 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado15() {
                return personalizado15;
            }

            /**
             * Sets the value of the personalizado15 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado15(String value) {
                this.personalizado15 = value;
            }

            /**
             * Gets the value of the personalizado16 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado16() {
                return personalizado16;
            }

            /**
             * Sets the value of the personalizado16 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado16(String value) {
                this.personalizado16 = value;
            }

            /**
             * Gets the value of the personalizado17 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado17() {
                return personalizado17;
            }

            /**
             * Sets the value of the personalizado17 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado17(String value) {
                this.personalizado17 = value;
            }

            /**
             * Gets the value of the personalizado18 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado18() {
                return personalizado18;
            }

            /**
             * Sets the value of the personalizado18 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado18(String value) {
                this.personalizado18 = value;
            }

            /**
             * Gets the value of the personalizado19 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado19() {
                return personalizado19;
            }

            /**
             * Sets the value of the personalizado19 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado19(String value) {
                this.personalizado19 = value;
            }

            /**
             * Gets the value of the personalizado20 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonalizado20() {
                return personalizado20;
            }

            /**
             * Sets the value of the personalizado20 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonalizado20(String value) {
                this.personalizado20 = value;
            }

            /**
             * Gets the value of the personalizado21 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPersonalizado21() {
                return personalizado21;
            }

            /**
             * Sets the value of the personalizado21 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPersonalizado21(BigInteger value) {
                this.personalizado21 = value;
            }

            /**
             * Gets the value of the personalizado22 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPersonalizado22() {
                return personalizado22;
            }

            /**
             * Sets the value of the personalizado22 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPersonalizado22(BigInteger value) {
                this.personalizado22 = value;
            }

            /**
             * Gets the value of the personalizado23 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPersonalizado23() {
                return personalizado23;
            }

            /**
             * Sets the value of the personalizado23 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPersonalizado23(BigInteger value) {
                this.personalizado23 = value;
            }

            /**
             * Gets the value of the personalizado24 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPersonalizado24() {
                return personalizado24;
            }

            /**
             * Sets the value of the personalizado24 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPersonalizado24(BigDecimal value) {
                this.personalizado24 = value;
            }

            /**
             * Gets the value of the personalizado25 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPersonalizado25() {
                return personalizado25;
            }

            /**
             * Sets the value of the personalizado25 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPersonalizado25(BigDecimal value) {
                this.personalizado25 = value;
            }

            /**
             * Gets the value of the personalizado26 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPersonalizado26() {
                return personalizado26;
            }

            /**
             * Sets the value of the personalizado26 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPersonalizado26(BigDecimal value) {
                this.personalizado26 = value;
            }

            /**
             * Gets the value of the personalizado27 property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPersonalizado27() {
                return personalizado27;
            }

            /**
             * Sets the value of the personalizado27 property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPersonalizado27(XMLGregorianCalendar value) {
                this.personalizado27 = value;
            }

            /**
             * Gets the value of the personalizado28 property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPersonalizado28() {
                return personalizado28;
            }

            /**
             * Sets the value of the personalizado28 property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPersonalizado28(XMLGregorianCalendar value) {
                this.personalizado28 = value;
            }

            /**
             * Gets the value of the personalizado29 property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPersonalizado29() {
                return personalizado29;
            }

            /**
             * Sets the value of the personalizado29 property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPersonalizado29(XMLGregorianCalendar value) {
                this.personalizado29 = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PersonNroLinDet" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="DetPersonAFN_01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonAFN_10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_01" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_02" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_03" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_04" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_05" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_06" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_07" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_08" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_09" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUE_10" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_01" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_02" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_03" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_04" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_05" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_06" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_07" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_08" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_09" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonNUD_10" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="DetPersonFEC_01" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="DetPersonFEC_02" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "personNroLinDet",
            "detPersonAFN01",
            "detPersonAFN02",
            "detPersonAFN03",
            "detPersonAFN04",
            "detPersonAFN05",
            "detPersonAFN06",
            "detPersonAFN07",
            "detPersonAFN08",
            "detPersonAFN09",
            "detPersonAFN10",
            "detPersonNUE01",
            "detPersonNUE02",
            "detPersonNUE03",
            "detPersonNUE04",
            "detPersonNUE05",
            "detPersonNUE06",
            "detPersonNUE07",
            "detPersonNUE08",
            "detPersonNUE09",
            "detPersonNUE10",
            "detPersonNUD01",
            "detPersonNUD02",
            "detPersonNUD03",
            "detPersonNUD04",
            "detPersonNUD05",
            "detPersonNUD06",
            "detPersonNUD07",
            "detPersonNUD08",
            "detPersonNUD09",
            "detPersonNUD10",
            "detPersonFEC01",
            "detPersonFEC02"
        })
        public static class ImpresionDetalle {

            @XmlElement(name = "PersonNroLinDet", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger personNroLinDet;
            @XmlElement(name = "DetPersonAFN_01")
            protected String detPersonAFN01;
            @XmlElement(name = "DetPersonAFN_02")
            protected String detPersonAFN02;
            @XmlElement(name = "DetPersonAFN_03")
            protected String detPersonAFN03;
            @XmlElement(name = "DetPersonAFN_04")
            protected String detPersonAFN04;
            @XmlElement(name = "DetPersonAFN_05")
            protected String detPersonAFN05;
            @XmlElement(name = "DetPersonAFN_06")
            protected String detPersonAFN06;
            @XmlElement(name = "DetPersonAFN_07")
            protected String detPersonAFN07;
            @XmlElement(name = "DetPersonAFN_08")
            protected String detPersonAFN08;
            @XmlElement(name = "DetPersonAFN_09")
            protected String detPersonAFN09;
            @XmlElement(name = "DetPersonAFN_10")
            protected String detPersonAFN10;
            @XmlElement(name = "DetPersonNUE_01")
            protected BigInteger detPersonNUE01;
            @XmlElement(name = "DetPersonNUE_02")
            protected BigInteger detPersonNUE02;
            @XmlElement(name = "DetPersonNUE_03")
            protected BigInteger detPersonNUE03;
            @XmlElement(name = "DetPersonNUE_04")
            protected BigInteger detPersonNUE04;
            @XmlElement(name = "DetPersonNUE_05")
            protected BigInteger detPersonNUE05;
            @XmlElement(name = "DetPersonNUE_06")
            protected BigInteger detPersonNUE06;
            @XmlElement(name = "DetPersonNUE_07")
            protected BigInteger detPersonNUE07;
            @XmlElement(name = "DetPersonNUE_08")
            protected BigInteger detPersonNUE08;
            @XmlElement(name = "DetPersonNUE_09")
            protected BigInteger detPersonNUE09;
            @XmlElement(name = "DetPersonNUE_10")
            protected BigInteger detPersonNUE10;
            @XmlElement(name = "DetPersonNUD_01")
            protected BigDecimal detPersonNUD01;
            @XmlElement(name = "DetPersonNUD_02")
            protected BigDecimal detPersonNUD02;
            @XmlElement(name = "DetPersonNUD_03")
            protected BigDecimal detPersonNUD03;
            @XmlElement(name = "DetPersonNUD_04")
            protected BigDecimal detPersonNUD04;
            @XmlElement(name = "DetPersonNUD_05")
            protected BigDecimal detPersonNUD05;
            @XmlElement(name = "DetPersonNUD_06")
            protected BigDecimal detPersonNUD06;
            @XmlElement(name = "DetPersonNUD_07")
            protected BigDecimal detPersonNUD07;
            @XmlElement(name = "DetPersonNUD_08")
            protected BigDecimal detPersonNUD08;
            @XmlElement(name = "DetPersonNUD_09")
            protected BigDecimal detPersonNUD09;
            @XmlElement(name = "DetPersonNUD_10")
            protected BigDecimal detPersonNUD10;
            @XmlElement(name = "DetPersonFEC_01")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar detPersonFEC01;
            @XmlElement(name = "DetPersonFEC_02")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar detPersonFEC02;

            /**
             * Gets the value of the personNroLinDet property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPersonNroLinDet() {
                return personNroLinDet;
            }

            /**
             * Sets the value of the personNroLinDet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPersonNroLinDet(BigInteger value) {
                this.personNroLinDet = value;
            }

            /**
             * Gets the value of the detPersonAFN01 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN01() {
                return detPersonAFN01;
            }

            /**
             * Sets the value of the detPersonAFN01 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN01(String value) {
                this.detPersonAFN01 = value;
            }

            /**
             * Gets the value of the detPersonAFN02 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN02() {
                return detPersonAFN02;
            }

            /**
             * Sets the value of the detPersonAFN02 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN02(String value) {
                this.detPersonAFN02 = value;
            }

            /**
             * Gets the value of the detPersonAFN03 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN03() {
                return detPersonAFN03;
            }

            /**
             * Sets the value of the detPersonAFN03 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN03(String value) {
                this.detPersonAFN03 = value;
            }

            /**
             * Gets the value of the detPersonAFN04 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN04() {
                return detPersonAFN04;
            }

            /**
             * Sets the value of the detPersonAFN04 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN04(String value) {
                this.detPersonAFN04 = value;
            }

            /**
             * Gets the value of the detPersonAFN05 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN05() {
                return detPersonAFN05;
            }

            /**
             * Sets the value of the detPersonAFN05 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN05(String value) {
                this.detPersonAFN05 = value;
            }

            /**
             * Gets the value of the detPersonAFN06 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN06() {
                return detPersonAFN06;
            }

            /**
             * Sets the value of the detPersonAFN06 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN06(String value) {
                this.detPersonAFN06 = value;
            }

            /**
             * Gets the value of the detPersonAFN07 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN07() {
                return detPersonAFN07;
            }

            /**
             * Sets the value of the detPersonAFN07 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN07(String value) {
                this.detPersonAFN07 = value;
            }

            /**
             * Gets the value of the detPersonAFN08 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN08() {
                return detPersonAFN08;
            }

            /**
             * Sets the value of the detPersonAFN08 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN08(String value) {
                this.detPersonAFN08 = value;
            }

            /**
             * Gets the value of the detPersonAFN09 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN09() {
                return detPersonAFN09;
            }

            /**
             * Sets the value of the detPersonAFN09 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN09(String value) {
                this.detPersonAFN09 = value;
            }

            /**
             * Gets the value of the detPersonAFN10 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetPersonAFN10() {
                return detPersonAFN10;
            }

            /**
             * Sets the value of the detPersonAFN10 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetPersonAFN10(String value) {
                this.detPersonAFN10 = value;
            }

            /**
             * Gets the value of the detPersonNUE01 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE01() {
                return detPersonNUE01;
            }

            /**
             * Sets the value of the detPersonNUE01 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE01(BigInteger value) {
                this.detPersonNUE01 = value;
            }

            /**
             * Gets the value of the detPersonNUE02 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE02() {
                return detPersonNUE02;
            }

            /**
             * Sets the value of the detPersonNUE02 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE02(BigInteger value) {
                this.detPersonNUE02 = value;
            }

            /**
             * Gets the value of the detPersonNUE03 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE03() {
                return detPersonNUE03;
            }

            /**
             * Sets the value of the detPersonNUE03 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE03(BigInteger value) {
                this.detPersonNUE03 = value;
            }

            /**
             * Gets the value of the detPersonNUE04 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE04() {
                return detPersonNUE04;
            }

            /**
             * Sets the value of the detPersonNUE04 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE04(BigInteger value) {
                this.detPersonNUE04 = value;
            }

            /**
             * Gets the value of the detPersonNUE05 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE05() {
                return detPersonNUE05;
            }

            /**
             * Sets the value of the detPersonNUE05 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE05(BigInteger value) {
                this.detPersonNUE05 = value;
            }

            /**
             * Gets the value of the detPersonNUE06 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE06() {
                return detPersonNUE06;
            }

            /**
             * Sets the value of the detPersonNUE06 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE06(BigInteger value) {
                this.detPersonNUE06 = value;
            }

            /**
             * Gets the value of the detPersonNUE07 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE07() {
                return detPersonNUE07;
            }

            /**
             * Sets the value of the detPersonNUE07 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE07(BigInteger value) {
                this.detPersonNUE07 = value;
            }

            /**
             * Gets the value of the detPersonNUE08 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE08() {
                return detPersonNUE08;
            }

            /**
             * Sets the value of the detPersonNUE08 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE08(BigInteger value) {
                this.detPersonNUE08 = value;
            }

            /**
             * Gets the value of the detPersonNUE09 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE09() {
                return detPersonNUE09;
            }

            /**
             * Sets the value of the detPersonNUE09 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE09(BigInteger value) {
                this.detPersonNUE09 = value;
            }

            /**
             * Gets the value of the detPersonNUE10 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDetPersonNUE10() {
                return detPersonNUE10;
            }

            /**
             * Sets the value of the detPersonNUE10 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDetPersonNUE10(BigInteger value) {
                this.detPersonNUE10 = value;
            }

            /**
             * Gets the value of the detPersonNUD01 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD01() {
                return detPersonNUD01;
            }

            /**
             * Sets the value of the detPersonNUD01 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD01(BigDecimal value) {
                this.detPersonNUD01 = value;
            }

            /**
             * Gets the value of the detPersonNUD02 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD02() {
                return detPersonNUD02;
            }

            /**
             * Sets the value of the detPersonNUD02 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD02(BigDecimal value) {
                this.detPersonNUD02 = value;
            }

            /**
             * Gets the value of the detPersonNUD03 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD03() {
                return detPersonNUD03;
            }

            /**
             * Sets the value of the detPersonNUD03 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD03(BigDecimal value) {
                this.detPersonNUD03 = value;
            }

            /**
             * Gets the value of the detPersonNUD04 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD04() {
                return detPersonNUD04;
            }

            /**
             * Sets the value of the detPersonNUD04 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD04(BigDecimal value) {
                this.detPersonNUD04 = value;
            }

            /**
             * Gets the value of the detPersonNUD05 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD05() {
                return detPersonNUD05;
            }

            /**
             * Sets the value of the detPersonNUD05 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD05(BigDecimal value) {
                this.detPersonNUD05 = value;
            }

            /**
             * Gets the value of the detPersonNUD06 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD06() {
                return detPersonNUD06;
            }

            /**
             * Sets the value of the detPersonNUD06 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD06(BigDecimal value) {
                this.detPersonNUD06 = value;
            }

            /**
             * Gets the value of the detPersonNUD07 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD07() {
                return detPersonNUD07;
            }

            /**
             * Sets the value of the detPersonNUD07 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD07(BigDecimal value) {
                this.detPersonNUD07 = value;
            }

            /**
             * Gets the value of the detPersonNUD08 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD08() {
                return detPersonNUD08;
            }

            /**
             * Sets the value of the detPersonNUD08 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD08(BigDecimal value) {
                this.detPersonNUD08 = value;
            }

            /**
             * Gets the value of the detPersonNUD09 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD09() {
                return detPersonNUD09;
            }

            /**
             * Sets the value of the detPersonNUD09 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD09(BigDecimal value) {
                this.detPersonNUD09 = value;
            }

            /**
             * Gets the value of the detPersonNUD10 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDetPersonNUD10() {
                return detPersonNUD10;
            }

            /**
             * Sets the value of the detPersonNUD10 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDetPersonNUD10(BigDecimal value) {
                this.detPersonNUD10 = value;
            }

            /**
             * Gets the value of the detPersonFEC01 property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDetPersonFEC01() {
                return detPersonFEC01;
            }

            /**
             * Sets the value of the detPersonFEC01 property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDetPersonFEC01(XMLGregorianCalendar value) {
                this.detPersonFEC01 = value;
            }

            /**
             * Gets the value of the detPersonFEC02 property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDetPersonFEC02() {
                return detPersonFEC02;
            }

            /**
             * Sets the value of the detPersonFEC02 property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDetPersonFEC02(XMLGregorianCalendar value) {
                this.detPersonFEC02 = value;
            }

        }

    }

}
