//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.14 at 12:18:35 PM GMT-03:00 
//


package cl.caserita.xsd.tipoDespacho;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoTipoDespacho" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="descripcionTipoDespacho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoTipoDespacho",
    "descripcionTipoDespacho"
})
@XmlRootElement(name = "tipoDespacho")
public class TipoDespacho {

    protected int codigoTipoDespacho;
    @XmlElement(required = true)
    protected String descripcionTipoDespacho;

    /**
     * Gets the value of the codigoTipoDespacho property.
     * 
     */
    public int getCodigoTipoDespacho() {
        return codigoTipoDespacho;
    }

    /**
     * Sets the value of the codigoTipoDespacho property.
     * 
     */
    public void setCodigoTipoDespacho(int value) {
        this.codigoTipoDespacho = value;
    }

    /**
     * Gets the value of the descripcionTipoDespacho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionTipoDespacho() {
        return descripcionTipoDespacho;
    }

    /**
     * Sets the value of the descripcionTipoDespacho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionTipoDespacho(String value) {
        this.descripcionTipoDespacho = value;
    }

}
