//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 12:05:46 PM CLT 
//


package cl.caserita.xsd.usuario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rutCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="digitoCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rutPersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="digitoPersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solicitud" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombrePersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoDespacho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionTipoDespacho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="villaPoblacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="celular" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoCiudad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionCiudad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoComuna" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionComuna" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="horario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoEstado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionEstado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoUsuario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactoRetiro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="observacionDespacho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitud" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="longitud" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correlativo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechaDespacho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoArticulo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionArticulo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoCaja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adicionales">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="apellidos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombreCompleto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rutCliente",
    "digitoCliente",
    "rutPersona",
    "digitoPersona",
    "password",
    "solicitud",
    "nombrePersona",
    "tipoDespacho",
    "descripcionTipoDespacho",
    "direccion",
    "numero",
    "villaPoblacion",
    "departamento",
    "celular",
    "telefono",
    "email",
    "codigoRegion",
    "descripcionRegion",
    "codigoCiudad",
    "descripcionCiudad",
    "codigoComuna",
    "descripcionComuna",
    "horario",
    "codigoEstado",
    "descripcionEstado",
    "tipoUsuario",
    "contactoRetiro",
    "observacionDespacho",
    "latitud",
    "longitud",
    "correlativo",
    "fechaDespacho",
    "codigoArticulo",
    "descripcionArticulo",
    "tipoCaja",
    "adicionales"
})
@XmlRootElement(name = "usuario")
public class Usuario {

    @XmlElement(required = true)
    protected String rutCliente;
    @XmlElement(required = true)
    protected String digitoCliente;
    @XmlElement(required = true)
    protected String rutPersona;
    @XmlElement(required = true)
    protected String digitoPersona;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String solicitud;
    @XmlElement(required = true)
    protected String nombrePersona;
    @XmlElement(required = true)
    protected String tipoDespacho;
    @XmlElement(required = true)
    protected String descripcionTipoDespacho;
    @XmlElement(required = true)
    protected String direccion;
    @XmlElement(required = true)
    protected String numero;
    @XmlElement(required = true)
    protected String villaPoblacion;
    @XmlElement(required = true)
    protected String departamento;
    @XmlElement(required = true)
    protected String celular;
    @XmlElement(required = true)
    protected String telefono;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String codigoRegion;
    @XmlElement(required = true)
    protected String descripcionRegion;
    @XmlElement(required = true)
    protected String codigoCiudad;
    @XmlElement(required = true)
    protected String descripcionCiudad;
    @XmlElement(required = true)
    protected String codigoComuna;
    @XmlElement(required = true)
    protected String descripcionComuna;
    @XmlElement(required = true)
    protected String horario;
    @XmlElement(required = true)
    protected String codigoEstado;
    @XmlElement(required = true)
    protected String descripcionEstado;
    @XmlElement(required = true)
    protected String tipoUsuario;
    @XmlElement(required = true)
    protected String contactoRetiro;
    @XmlElement(required = true)
    protected String observacionDespacho;
    @XmlElement(required = true)
    protected String latitud;
    @XmlElement(required = true)
    protected String longitud;
    @XmlElement(required = true)
    protected String correlativo;
    @XmlElement(required = true)
    protected String fechaDespacho;
    @XmlElement(required = true)
    protected String codigoArticulo;
    @XmlElement(required = true)
    protected String descripcionArticulo;
    @XmlElement(required = true)
    protected String tipoCaja;
    @XmlElement(required = true)
    protected Usuario.Adicionales adicionales;

    /**
     * Gets the value of the rutCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutCliente() {
        return rutCliente;
    }

    /**
     * Sets the value of the rutCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutCliente(String value) {
        this.rutCliente = value;
    }

    /**
     * Gets the value of the digitoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitoCliente() {
        return digitoCliente;
    }

    /**
     * Sets the value of the digitoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitoCliente(String value) {
        this.digitoCliente = value;
    }

    /**
     * Gets the value of the rutPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutPersona() {
        return rutPersona;
    }

    /**
     * Sets the value of the rutPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutPersona(String value) {
        this.rutPersona = value;
    }

    /**
     * Gets the value of the digitoPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitoPersona() {
        return digitoPersona;
    }

    /**
     * Sets the value of the digitoPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitoPersona(String value) {
        this.digitoPersona = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the solicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolicitud() {
        return solicitud;
    }

    /**
     * Sets the value of the solicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolicitud(String value) {
        this.solicitud = value;
    }

    /**
     * Gets the value of the nombrePersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrePersona() {
        return nombrePersona;
    }

    /**
     * Sets the value of the nombrePersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrePersona(String value) {
        this.nombrePersona = value;
    }

    /**
     * Gets the value of the tipoDespacho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDespacho() {
        return tipoDespacho;
    }

    /**
     * Sets the value of the tipoDespacho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDespacho(String value) {
        this.tipoDespacho = value;
    }

    /**
     * Gets the value of the descripcionTipoDespacho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionTipoDespacho() {
        return descripcionTipoDespacho;
    }

    /**
     * Sets the value of the descripcionTipoDespacho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionTipoDespacho(String value) {
        this.descripcionTipoDespacho = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the villaPoblacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVillaPoblacion() {
        return villaPoblacion;
    }

    /**
     * Sets the value of the villaPoblacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVillaPoblacion(String value) {
        this.villaPoblacion = value;
    }

    /**
     * Gets the value of the departamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartamento() {
        return departamento;
    }

    /**
     * Sets the value of the departamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartamento(String value) {
        this.departamento = value;
    }

    /**
     * Gets the value of the celular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCelular() {
        return celular;
    }

    /**
     * Sets the value of the celular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCelular(String value) {
        this.celular = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the codigoRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoRegion() {
        return codigoRegion;
    }

    /**
     * Sets the value of the codigoRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoRegion(String value) {
        this.codigoRegion = value;
    }

    /**
     * Gets the value of the descripcionRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionRegion() {
        return descripcionRegion;
    }

    /**
     * Sets the value of the descripcionRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionRegion(String value) {
        this.descripcionRegion = value;
    }

    /**
     * Gets the value of the codigoCiudad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCiudad() {
        return codigoCiudad;
    }

    /**
     * Sets the value of the codigoCiudad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCiudad(String value) {
        this.codigoCiudad = value;
    }

    /**
     * Gets the value of the descripcionCiudad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionCiudad() {
        return descripcionCiudad;
    }

    /**
     * Sets the value of the descripcionCiudad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionCiudad(String value) {
        this.descripcionCiudad = value;
    }

    /**
     * Gets the value of the codigoComuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoComuna() {
        return codigoComuna;
    }

    /**
     * Sets the value of the codigoComuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoComuna(String value) {
        this.codigoComuna = value;
    }

    /**
     * Gets the value of the descripcionComuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionComuna() {
        return descripcionComuna;
    }

    /**
     * Sets the value of the descripcionComuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionComuna(String value) {
        this.descripcionComuna = value;
    }

    /**
     * Gets the value of the horario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorario() {
        return horario;
    }

    /**
     * Sets the value of the horario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorario(String value) {
        this.horario = value;
    }

    /**
     * Gets the value of the codigoEstado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoEstado() {
        return codigoEstado;
    }

    /**
     * Sets the value of the codigoEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoEstado(String value) {
        this.codigoEstado = value;
    }

    /**
     * Gets the value of the descripcionEstado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionEstado() {
        return descripcionEstado;
    }

    /**
     * Sets the value of the descripcionEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionEstado(String value) {
        this.descripcionEstado = value;
    }

    /**
     * Gets the value of the tipoUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoUsuario() {
        return tipoUsuario;
    }

    /**
     * Sets the value of the tipoUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoUsuario(String value) {
        this.tipoUsuario = value;
    }

    /**
     * Gets the value of the contactoRetiro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactoRetiro() {
        return contactoRetiro;
    }

    /**
     * Sets the value of the contactoRetiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactoRetiro(String value) {
        this.contactoRetiro = value;
    }

    /**
     * Gets the value of the observacionDespacho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacionDespacho() {
        return observacionDespacho;
    }

    /**
     * Sets the value of the observacionDespacho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacionDespacho(String value) {
        this.observacionDespacho = value;
    }

    /**
     * Gets the value of the latitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * Sets the value of the latitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitud(String value) {
        this.latitud = value;
    }

    /**
     * Gets the value of the longitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitud() {
        return longitud;
    }

    /**
     * Sets the value of the longitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitud(String value) {
        this.longitud = value;
    }

    /**
     * Gets the value of the correlativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelativo() {
        return correlativo;
    }

    /**
     * Sets the value of the correlativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelativo(String value) {
        this.correlativo = value;
    }

    /**
     * Gets the value of the fechaDespacho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaDespacho() {
        return fechaDespacho;
    }

    /**
     * Sets the value of the fechaDespacho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaDespacho(String value) {
        this.fechaDespacho = value;
    }

    /**
     * Gets the value of the codigoArticulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoArticulo() {
        return codigoArticulo;
    }

    /**
     * Sets the value of the codigoArticulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoArticulo(String value) {
        this.codigoArticulo = value;
    }

    /**
     * Gets the value of the descripcionArticulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionArticulo() {
        return descripcionArticulo;
    }

    /**
     * Sets the value of the descripcionArticulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionArticulo(String value) {
        this.descripcionArticulo = value;
    }

    /**
     * Gets the value of the tipoCaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCaja() {
        return tipoCaja;
    }

    /**
     * Sets the value of the tipoCaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCaja(String value) {
        this.tipoCaja = value;
    }

    /**
     * Gets the value of the adicionales property.
     * 
     * @return
     *     possible object is
     *     {@link Usuario.Adicionales }
     *     
     */
    public Usuario.Adicionales getAdicionales() {
        return adicionales;
    }

    /**
     * Sets the value of the adicionales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usuario.Adicionales }
     *     
     */
    public void setAdicionales(Usuario.Adicionales value) {
        this.adicionales = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="apellidos" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nombreCompleto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fechaNacimiento",
        "nombres",
        "apellidos",
        "nombreCompleto"
    })
    public static class Adicionales {

        @XmlElement(required = true)
        protected String fechaNacimiento;
        @XmlElement(required = true)
        protected String nombres;
        @XmlElement(required = true)
        protected String apellidos;
        @XmlElement(required = true)
        protected String nombreCompleto;

        /**
         * Gets the value of the fechaNacimiento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaNacimiento() {
            return fechaNacimiento;
        }

        /**
         * Sets the value of the fechaNacimiento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaNacimiento(String value) {
            this.fechaNacimiento = value;
        }

        /**
         * Gets the value of the nombres property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombres() {
            return nombres;
        }

        /**
         * Sets the value of the nombres property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombres(String value) {
            this.nombres = value;
        }

        /**
         * Gets the value of the apellidos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApellidos() {
            return apellidos;
        }

        /**
         * Sets the value of the apellidos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApellidos(String value) {
            this.apellidos = value;
        }

        /**
         * Gets the value of the nombreCompleto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreCompleto() {
            return nombreCompleto;
        }

        /**
         * Sets the value of the nombreCompleto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreCompleto(String value) {
            this.nombreCompleto = value;
        }

    }

}
