//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 05:58:20 PM CLT 
//


package cl.sii.envioDTE;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedioPagoType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MedioPagoType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="EF"/>
 *     &lt;enumeration value="PE"/>
 *     &lt;enumeration value="TC"/>
 *     &lt;enumeration value="CF"/>
 *     &lt;enumeration value="OT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MedioPagoType", namespace = "http://www.sii.cl/SiiDte")
@XmlEnum
public enum MedioPagoType {

    CH,
    LT,
    EF,
    PE,
    TC,
    CF,
    OT;

    public String value() {
        return name();
    }

    public static MedioPagoType fromValue(String v) {
        return valueOf(v);
    }

}
